default: true
MD013: false
MD033: false
MD041: false
MD024:
  siblings_only: true
MD025:
  level: 1
MD026:
  punctuation: ".,;:!"
MD029:
  style: ordered
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1
